### PR TITLE
Fix missing proxy auth

### LINKED ISSUE #39: Proxy authentication should not be configured if no proxy username/password is provided
Looks like http-client is passing an invalid proxy authentication header if no proxy authentication was provided at all here https://github.com/actions/http-client/blob/edadda14b09058389cd47f9790e19b97883624c1/index.ts#L641-L649

If a proxy server doesn't require authentication (which is an example of our company proxies), we're sending `proxyAuth: ':'` which ends up on being a real authentication header passed to the client and tells proxy to try validate credentials, which they will be incorrect.

Otherwise the underlaying http library for creating the tunnel will set that proxy header if proxyAuth contains a value https://github.com/request/tunnel-agent/blob/master/index.js#L128-L132

Proxy Auth should not be set if username/password is not provided

### PR DESCRIPTION
**Pull request by pravipati**
Fixes #39 by adding check to see whether proxy authentication is provided

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -642,7 +642,7 @@ export class HttpClient {
         maxSockets: maxSockets,
         keepAlive: this._keepAlive,
         proxy: {
-          proxyAuth: `${proxyUrl.username}:${proxyUrl.password}`,
+          ...((proxyUrl.username || proxyUrl.password) && { proxyAuth: `${proxyUrl.username}:${proxyUrl.password}` }),
```
Comment (bryanmacfarlane) [inline index.ts:645]: the change looks good. On a related note, I wonder if it should be proxyUrl.username && proxyUrl.password?  if username is set but password isn't (or vice versa) would we want to set it?  The other option is to just check if proxyUrl.username is set because apparently a nul password is valid (see [mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=32761))

Comment (bhilton) [reply index.ts:645]: I would suggest setting it if either username or password is defined. It's up to the given authentication backend to handle the nuances. For example, authenticating with Github via only a token (in the password field) is perfectly valid.

Comment (bryanmacfarlane) [reply index.ts:645]: makes sense.

**Comment by bryanmacfarlane** [comment]
changes look good.  I think you need to run format on the code so the prettier check passes (it only runs on the linux leg - see the failed run)

File: index.ts (hunk 1 above)
Comment (fgalind1) [inline index.ts:645]: this should prettify the code :)

```suggestion
          ...((proxyUrl.username || proxyUrl.password) && {
            proxyAuth: `${proxyUrl.username}:${proxyUrl.password}`
          }),
```

File: __tests__/proxy.test.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@ import * as http from 'http'
 import * as httpm from '../_out'
 import * as pm from '../_out/proxy'
 import * as proxy from 'proxy'
```
Comment (jen801) [inline __tests__/proxy.test.ts:4]: index.ts

File: __tests__/proxy.test.ts [hunk 3]
```diff
@@ -2,6 +2,7 @@ import * as http from 'http'
...
+import * as tunnelm from 'tunnel'
```
Comment (jen801) [inline __tests__/proxy.test.ts:5]: __tests__/proxy.test.ts

**Review by jen801 — COMMENTED** [review]
Duplicate of #

File: __tests__/proxy.test.ts (hunk 2 above)
Comment (jen801) [reply __tests__/proxy.test.ts:4]: __tests__/proxy.test.ts

**Review by jen801 — COMMENTED** [review]
__tests__/proxy.test.ts
